/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CRS.UI;

import CRS.Applogic.Student;
import CRS.Applogic.StudentModel;
import java.util.List;
import java.util.Observable;
import java.util.Observer;
import javax.swing.DefaultListModel;

/**
 *
 * @author aashgar
 */
public class StudentsView extends javax.swing.JPanel 
    implements Observer{
    private StudentModel aStudentModel;

    public void setaStudentModel(StudentModel aStudentModel) {
        this.aStudentModel = aStudentModel;
    }

    /**
     * Creates new form StudentsView
     */
    public StudentsView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jListStudents = new javax.swing.JList();

        jListStudents.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jListStudents);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList jListStudents;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object arg) {
        List<Student> students = ((StudentModel) o).getStudents();
        DefaultListModel aDefaultListModel = new
            DefaultListModel();
        aDefaultListModel.addElement("  Name -- Major -- Grade");
        aDefaultListModel.addElement("========================");
        for(Student aStudent: students){
            aDefaultListModel.addElement(aStudent.getName() + " -- "+
                    aStudent.getMajor()+ " -- "+
                    aStudent.getGrade());
        }
        jListStudents.setModel(aDefaultListModel);
    }
}
